project:
  type: book
  pre-render: R/setup.R

callout-appearance: simple
# see this quarto discussion issue for info on lua filter
# https://github.com/quarto-dev/quarto-cli/discussions/2869#discussioncomment-3886253
filters: 
 - chapters/lua/callouts.lua

execute:
  freeze: auto  
  echo: true 
  dev: "ragg_png"
  dpi: 740 
  out.width: "80%"
  fig.width: 6
  fig.asp: 0.618
  fig.retina: 3
  fig.align: "center"
  fig.show: "hold"
  
book:
  title: "Causal Inference in R"
  author: ["Malcolm Barrett", "Lucy D'Agostino McGowan", "Travis Gerke"]
  date: "today"
  repo-url: https://github.com/malcolmbarrett/causal-inference-in-r
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    
    - part: Asking Causal Questions
      chapters: 
      - chapters/01-casual-to-causal.qmd
      - chapters/02-whole-game.qmd
      - chapters/03-counterfactuals.qmd
      - chapters/04-target-trials-std-methods.qmd
      - chapters/05-dags.qmd
      - chapters/06-not-just-a-stats-problem.qmd
      
    - part: The Design Phase 
      chapters: 
      - chapters/07-prep-data.qmd
      - chapters/08-building-ps-models.qmd
      - chapters/09-using-ps.qmd
      - chapters/10-evaluating-ps.qmd
      
    - part: Estimating Causal Effects 
      chapters: 
      - chapters/11-estimands.qmd
      - chapters/12-outcome-model.qmd
      - chapters/13-continuous-exposures.qmd
      - chapters/14-categorical-exposures.qmd
      - chapters/15-g-comp.qmd
      - chapters/16-interaction.qmd
      - chapters/17-missingness-and-measurement.qmd
      - chapters/18-longitudinal.qmd
      - chapters/19-survival.qmd
      - chapters/20-mediation.qmd
      - chapters/21-sensitivity.qmd
      - chapters/22-machine-learning.qmd
      - chapters/23-iv-and-friends.qmd
      - chapters/24-evidence.qmd
      
    - chapters/99-references.qmd
      
bibliography: citations.bib

format:
  html:
    code-link: true
    tbl-cap-location: bottom
    theme:
      - cosmo
      - style.scss
    include-in-header: "plausible.html"
  #pdf:
    #tbl-cap-location: bottom
    #documentclass: krantz
    #link-citations: true
    #colorlinks: true
    #lot: true
    #lof: true
    #includes:
    #  in_header: latex/preamble.tex
    #  before_body: latex/before_body.tex
    #  after_body: latex/after_body.tex

editor_options:
  markdown:
    wrap: sentence
    canonical: true
    
